channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numba
  - nodejs=8.9
  - notebook
  - nbconvert=5.3
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - bqplot=0.10
  - dask=0.15
  - matplotlib=2.1
  - pandas=0.20
  - python=3.6
  - seaborn=0.7
  - sympy=1.0
  - pyyaml
  - traittypes==0.0.6
  - invoke=0.21
  - matplotlib
  - numpy
  - fortran-magic 
  - cython
  - rpy2
  - pip
  - pip:
      - julia
      - cffi_magic
      - bash_kernel
      - py3Dmol
      
  
